# Week2授業前課題3
## 行列積のスクラッチ
行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

以下のような行列A、Bを考えます。

$$
A=\begin{bmatrix}
    -1 & 2 & 3 \\
    4 & -5 & 6 \\
    7 & 8 & -9
\end{bmatrix},
B=\begin{bmatrix}
    0 & 2 & 1 \\
    0 & 2 & -8 \\
    2 & 9 & -1
\end{bmatrix}
$$

NumPyで表すと次のようになります。

```python
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
```

# 問題1
## 行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

## 行列積の定義（2次元）
$n \times m$行列$A$と$m \times p$行列$B$を、
$$
A=\begin{bmatrix}
      a_{11} & a_{12} & \ldots & a_{1m} \\
      a_{21} & a_{22} & \ldots & a_{2m} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{n1} & a_{n2} & \ldots & a_{nm}
\end{bmatrix},\quad
B=\begin{bmatrix}
      b_{11} & b_{12} & \ldots & b_{1p} \\
      b_{21} & b_{22} & \ldots & b_{2p} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mp}
\end{bmatrix}
$$
とするとき、これらの行列の積$AB$を
$$
AB=\begin{bmatrix}
      c_{11} & c_{12} & \ldots & c_{1p} \\
      c_{21} & c_{22} & \ldots & c_{2p} \\
      \vdots & \vdots & \ddots & \vdots \\
      c_{n1} & c_{n2} & \ldots & c_{np}
\end{bmatrix}
$$
と表す。
すると、行列$AB$のそれぞれの要素$c_{ij}$は、
$$
c_{ij}=\sum_{k=1}^{m}a_{ik}b_{kj}\qquad
\begin{pmatrix}
      i=1,2,\ldots,n \\
      j=1,2,\ldots,p
\end{pmatrix}
$$
で表される。

よって、

$$
\begin{align*}
      c_{11}&=(-1)\times0+2\times0+3\times2=6\\
      c_{12}&=(-1)\times2+2\times2+3\times9=29\\
      c_{13}&=(-1)\times1+2\times(-8)+3\times(-1)=-20\\
      c_{21}&=4\times0+(-5)\times0+6\times2=12\\
      c_{22}&=4\times2+(-5)\times2+6\times9=52\\
      c_{23}&=4\times1+(-5)\times(-8)+6\times(-1)=38\\
      c_{31}&=7\times0+8\times0+(-9)\times2=-18\\
      c_{32}&=7\times2+8\times2+(-9)\times9=-51\\
      c_{33}&=7\times1+8\times(-8)+(-9)\times(-1)=-48
\end{align*}
$$

となるから、

$$
AB=\begin{bmatrix}
      6 & 29 & -20 \\
      12 & 52 & 38 \\
      -18 & -51 & -48
\end{bmatrix}
$$

# 問題2
## NumPyの関数による計算
この行列積はNumPyの`np.matmul()`や`np.dot()`、または`@`演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

In [3]:
# 公式に推奨されるnp.matmul()を使用する
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 問題3
## ある要素の計算を実行
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


- 行列Aの(0,0)の要素$a_{0,0}$と行列Bの(0,0)の要素$b_{0,0}$を掛け合わせる
- 行列Aの(0,1)の要素$a_{0,1}$と行列Bの(1,0)の要素$b_{1,0}$を掛け合わせる
- 行列Aの(0,2)の要素$a_{0,2}$と行列Bの(2,0)の要素$b_{2,0}$を掛け合わせる
- それらの値を全て足し合わせる

数式で表すと

$$
\sum_{k=0}^{2}a_{0,k}b_{k,0}
$$

です。


この計算を`np.matmul()`や`np.dot()`、または`@`演算子を使わずに行うコードを書いてください。

In [19]:
c_00 = a_ndarray[0][0]*b_ndarray[0][0] + a_ndarray[0][1]*b_ndarray[1][0] + a_ndarray[0][2]*b_ndarray[2][0]
print(c_00)

6


# 問題4
## 行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である$3\times3$の行列Cの各要素$c_{i,j}$は数式で表すと次のようになります。

$$
c_{i,j}=\sum_{k=0}^{2}a_{i,j}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス$i$や$j$を1増やすと、次の行や列に移ることができます。

In [15]:
# c = ab(行列aと行列bの積)
def matrix_multiple(a, b):
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i][j] = sum([a[i][k]*b[k][j] for k in range(a.shape[1])])
    return c

c_ndarray = matrix_multiple(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


次に以下のような例を考えます。

$$
D=\begin{bmatrix}
    -1 & 2 & 3 \\
    4 & -5 & 6
\end{bmatrix},\quad
E=\begin{bmatrix}
    -9 & 8 & 7 \\
    6 & -5 & 4
\end{bmatrix}
$$

```python
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
```

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

# 問題5
## 計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

In [20]:
def advanced_matrix_multiple(a, b):
    if a.shape[1]!=b.shape[0]:
        print('Cannot define multiplication!')
        return -1
    else:
        return matrix_multiple(a, b)

# エラーを発生させてみる
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(advanced_matrix_multiple(d_ndarray, e_ndarray))

Cannot define multiplication!
-1


# 問題6
## 転置
片方の行列を転置することで、行列積が計算できるようになります。


`np.transpose()`や`.T`アトリビュートを用いて転置し、行列積を計算してください。

In [21]:
# np.transpose()
print(advanced_matrix_multiple(np.transpose(d_ndarray), e_ndarray))

# .T
print(advanced_matrix_multiple(d_ndarray, e_ndarray.T))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
[[ 46.  -4.]
 [-34.  73.]]
