# Week4授業前課題3
## オブジェクト指向の活用
これまで使用してきたクラスを元にしてオブジェクト指向を理解していきます。

# 【問題1】
## これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

# Pandas
- pandas.DataFrame

表型のデータ形式
- pandas.Series

一次元のデータ形式

# matplotlib
- matplotlib.figure.Figure

プロットの図全体
- matplotlib.axes.Axes

プロットの座標軸
# scikit-learn

- sklearn.neighbors.KNeighborsClassifier

k近傍法によるクラス分類モデル
- sklearn.linear_model.LinearRegression

線形回帰モデル

# 【問題2】
## これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

# Pandas
- pandas.DataFrame.shape

DataFrameの形状
- pandas.DataFrame.values

DataFrameが保持しているnumpy.ndarray形式のデータ
- pandas.read_csv

csvデータを読み込みDataFrame形式にして返す
- pandas.Series.loc

列と行のラベルを持っており、抽出操作に有効
- pandas.Series.value_counts

Series内の一意な値の数を返す

# matplotlib
- matplotlib.pyplot.figure

Figure型のインスタンスを返す
- matplotlib.pyplot.show

すべての図を表示する
- matplotlib.figure.Figure.subplot

図に新たな座標軸を追加し、返す
- matplotlib.pyplot.suptitle

図にタイトルを記入する
- matplotlib.axes.Axes.set_xticklabels

対象となる座標軸のx軸に目盛りラベルを記入する

# scikit-learn
- sklearn.model_selection.train_test_split

データを訓練データとテストデータにランダム分割する
- sklearn.preprocessing.StandardScaler.fit

データの標準化のため、平均と分散を設定する
- sklearn.preprocessing.StandardScaler.transform

標準化を実行する
- sklearn.metrics.accuracy_score

予測結果から正解率を算出する
- sklearn.metrics.mean_squared_error

予測結果から平均二乗誤差を算出する

# 【問題3】
## 標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。

インスタンス変数を作成する際は`self.mean_`のようにselfを付けます。クラスの外から`scaler.mean_`と書いていたscalerの部分が自分自身を表すselfになっています。

In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        (追記: おそらく「平均と分散」？)

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        pass
        return X_scaled

In [2]:
# 動作テスト
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [3]:
# 平均・分散の変化を確認
print(X.mean(axis=0), X.var(axis=0))
print(X)
print(X_std.mean(axis=0), X_std.var(axis=0))
print(X_std)

[4.86 3.31 1.45 0.22] [0.0764 0.0849 0.0105 0.0056]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[ 2.23709939e-15  1.36557432e-15  0.00000000e+00 -2.88657986e-16] [1. 1. 1. 1.]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


ソースコードの中に含まれる、まだ説明していない重要な部分が以下です。

このような__init__というメソッドは、どのクラスにも共通して置かれる **コンストラクタ** と呼ばれるメソッドです。

```python
def __init__(self, copy=True, with_mean=True, with_std=True):
    self.with_mean = with_mean
    self.with_std = with_std
    self.copy = copy
```

今回のスクラッチではcopy、with_mean、with_stdなどのパラメータを省略しましたが、このようにインスタンス化の際にパラメータを指定して保存しておくということはよくある使い方です。

コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、 **特殊メソッド** と呼びます。

In [4]:
# Sample Code
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


# 【問題4】
## 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [5]:
class Arithmetics():
    """
    valueの四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.check_type(value)
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def check_type(self, arg):
        """
        数字以外が引数になったときエラーを返す
        """
        if not isinstance(arg, (int, float)):
            raise TypeError(f"'{arg}' is not a number.")
    def add(self, value2):
        """
        加算
        """
        self.check_type(value2)
        self.value += value2
    def sub(self, value2):
        """
        減算
        """
        self.check_type(value2)
        self.value -= value2
    def mul(self, value2):
        """
        乗算
        """
        self.check_type(value2)
        self.value *= value2
    def div(self, value2):
        """
        除算
        """
        self.check_type(value2)
        self.value /= value2

In [6]:
# 動作確認
# 正常値
val = Arithmetics(3)
print("value : {}".format(val.value))
val.add(3)
print("value : {}".format(val.value))
val.sub(2)
print("value : {}".format(val.value))
val.mul(4)
print("value : {}".format(val.value))
val.div(5)
print("value : {}".format(val.value))

初期値3が設定されました
value : 3
value : 6
value : 4
value : 16
value : 3.2


In [7]:
# 異常値 - 文字列
val.add('str')
print("value : {}".format(val.value))

TypeError: 'str' is not a number.

In [8]:
# 異常値 - 配列
val.mul([11, 6, 3])
print("value : {}".format(val.value))

TypeError: '[11, 6, 3]' is not a number.