In [1]:
import numpy as np
arr = np.arange(10)

In [2]:
print(arr[3])
print(arr[:3])
print(arr[-1])
print(arr[::2])
print(arr[::-1])

3
[0 1 2]
9
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [3]:
arr1 = np.arange(4)
print(arr1.shape)
arr2 = arr1.reshape(2,2)
print(arr2)
print(arr2.shape)

(4,)
[[0 1]
 [2 3]]
(2, 2)


In [8]:
arr3 = np.arange(6).reshape(2,3)
print(arr3)
print(arr3[1,2])
print(arr3[::,1::])

[[0 1 2]
 [3 4 5]]
5
[[1 2]
 [4 5]]


In [9]:
arr4 = np.arange(6)
arr5 = arr4.reshape(2,3)
print(arr5)
print("shape: {}".format(arr5.shape))
print("sum: {}".format(arr5.sum()))
print("0 axis sum: {}".format(arr5.sum(axis=0)))
print("1 axis ave: {}".format(arr5.mean(axis=1)))

[[0 1 2]
 [3 4 5]]
shape: (2, 3)
sum: 15
0 axis sum: [3 5 7]
1 axis ave: [1. 4.]
